Repository dis-moi/mobile, pull requests merged in 2021-07, with the labels that each got.

#144 bug/doNotLetBubbleAppearMoreThan1Time
  android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
  android/app/src/main/java/com/dismoi/scout/floating/FloatingModule.kt
  android/app/src/main/java/com/dismoi/scout/floating/FloatingService.kt
  android/app/src/main/res/layout/message.xml
  src/headlessTask/index.js
  src/libraries/index.js
Labels: M :shirt:, bug, refacto

#147 fix(accessibility): missing React effect cleanup
  src/useEffectHooks/nativeModules/accessibilityService/sendMessage/checkIfAccessibilityIsEnabled.js
Labels: refacto

#157 bug: don't perform a react state update on an unmounted component
  src/screens/authorizations.js
  src/useEffectHooks/everythingIsReady.js
  src/useEffectHooks/handleContributors.js
  src/useEffectHooks/nativeModules/accessibilityService/listenMessage/eventToListen.js
  src/useEffectHooks/nativeModules/accessibilityService/sendMessage/checkIfCanDrawOverlayIsEnabled.js
  src/useEffectHooks/startBackgroundService.js
Labels: bug

#165 bug: bubble disappear when user taps screen
  android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
  src/headlessTask/index.js
Labels: M :shirt:, bug

#158 Feat/add loader in contribution list
  src/screens/finished.js
Labels: S :shirt:

#164 Feat/use x path matching context
  android/app/build.gradle
  android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundModule.kt
  android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
  android/build.gradle
  src/headlessTask/index.js
Labels: L :shirt:, feature

#166 feat: limit accessibility access
  activity_main.xml
  android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
  android/app/src/main/res/xml/accessibility_service_config.xml
Labels: M :shirt:, feature

#167 feat: change copy of android authorization service page
  android/app/src/main/res/values/strings.xml
Labels: S :shirt:, feature

#168 feat: merge step 1 and 2
  src/navigations/onboarding.js
  src/screens/tuto1.js
  src/screens/tuto2.js
  src/screens/tuto3.js
  src/screens/welcome.js
Labels: S :shirt:, feature

#169 feat: swap authorization order
  src/screens/authorizations.js
Labels: XS :shirt:, feature, question

#170 bug: bubble does not appear because the accessibility is less torerant
  android/app/build.gradle
  android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
  android/app/src/main/java/com/dismoi/scout/floating/FloatingModule.kt
  android/app/src/main/java/com/dismoi/scout/floating/FloatingService.kt
  android/build.gradle
  src/headlessTask/index.js
Labels: L :shirt:, bug

#177 Refacto/correct kotlin warnings
  android/app/build.gradle
  android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
  android/app/src/main/java/com/dismoi/scout/floating/FloatingModule.kt
  android/app/src/main/java/com/dismoi/scout/floating/FloatingService.kt
  android/app/src/main/java/com/dismoi/scout/floating/Manager.kt
  android/app/src/main/java/com/dismoi/scout/floating/layout/Bubble.kt
  android/app/src/main/java/com/dismoi/scout/floating/layout/Layout.kt
  android/app/src/main/java/com/dismoi/scout/floating/layout/Message.kt
  android/app/src/main/java/com/dismoi/scout/floating/layout/Trash.kt
  android/build.gradle
  src/headlessTask/index.js
Labels: M :shirt:, refacto

#187 feat: contribution ui refinment
  android/app/src/main/res/drawable/close.xml
  android/app/src/main/res/layout/highlight_messages.xml
  android/app/src/main/res/layout/message.xml
  src/components/button.js
  src/components/paragraph.js
  src/components/radioButtons.js
  src/components/text.js
  src/components/title.js
  src/screens/finished.js
Labels: M :shirt:, MVP, feature

#188 Bug/bubble stays when chrome is closed
  android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
  android/app/src/main/java/com/dismoi/scout/floating/FloatingModule.kt
Labels: M :shirt:, bug

#189 bug: scroll stop contributor list
  src/screens/finished.js
Labels: M :shirt:, bug

#191 Bug/contributor list updates slowly
  src/screens/finished.js
  src/useEffectHooks/handleContributors.js
Labels: S :shirt:, bug

#192 refacto: adding some comments
  android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
Labels: XS :shirt:, refacto

#194 refacto: remove global variables
  src/headlessTask/index.js
Labels: XS :shirt:, refacto

#193 Bug/make bubble appear one time
  android/app/build.gradle
  android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
  android/app/src/main/java/com/dismoi/scout/floating/FloatingModule.kt
  src/headlessTask/index.js
  src/screens/finished.js
Labels: L :shirt:, MVP, bug

#195 Bug/make bubble disappear when launcher is activated or chrome is closed
  android/app/build.gradle
  android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
  android/app/src/main/java/com/dismoi/scout/floating/FloatingModule.kt
  android/app/src/main/java/com/dismoi/scout/floating/FloatingService.kt
  src/headlessTask/index.js
Labels: bug

#196 Bug reporting
  .github/ISSUE_TEMPLATE/Bugs.md
  .github/ISSUE_TEMPLATE/installation-issues.md
  .github/ISSUE_TEMPLATE/test-scenarii.md
Labels: feature

#207 WIP: Refactor accessibility service
  android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
  android/app/src/main/java/com/dismoi/scout/browser/SupportedBrowserConfig.kt
  android/app/src/main/java/com/dismoi/scout/browser/SupportedBrowsers.kt
Labels: refacto

#206 docs: create new scenarios
  .github/ISSUE_TEMPLATE/test-scenarii.md
Labels: S :shirt:
